server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  redis:
    port: 16379
    password: ENC(o0K+mAHRQzhK+pipW5NHp+Ttt4yG3lp0FpHZkn31mCwhJApVHy1e3lxA28hZhP0Y)
    host: redis.lingxiaomz.top

jasypt:
  encryptor:
    password: lE1rl5K$
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true   # 开启mybatis驼峰式命名规则
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: debug
  config: classpath:logback.xml
jwt:
  secret: blog@Login(Auth}*^31)&lingxiao% # 登录校验的密钥
  pubKeyPath: E:\\rsakey\\rsa.pub  # 公钥地址
  priKeyPath: E:\\rsakey\\rsa.pri  # 私钥地址
  expire: 30 # 过期时间,单位分钟
  cookieName: BLOG_COOKIE # cookie的名字
  cookieMaxAge: 30 # cookie的有效时长

oss:
  accessKey: ENC(CDrAPbLn1ms26K8bV1+YftOxb4JkrtfdSfa6/Rk60D9sPM8Fz5yM0SctICOGdYwlm66En2719qfoD8/cv4xbeJJkI930D1q3533zYxNKYwI=) # 设置好账号的ACCESS_KEY和SECRET_KEY
  secretKey: ENC(xKj7NFWTv+frIYmyHb6/uK7p94g2N4FHJGcAtlW0vVRr8ueBbtcNNWSEuOXof5UPNBH7o6TJOzR7PmiesU7EdLTnA80G+XBrM6UhBZ8zYiw=)
  bucketName: function  # 要上传的空间
  prefixImg: http://img.lingxiaomz.top/
  temporaryFolder: E:\bingImage\

email:
  title: '注册博客'
  minute: 5  #邮件有效时间  单位：分钟
ipregion:
  path: classpath:ip2region.db