server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&useSSL=false
    username: ENC(Jj9EiWU2ydbCb+mp5u+bTXXDbU/34lcKcdCvSULoeOraCCICab685zzpUuMpM5Ec)
    password: ENC(2CcNrJlIaWSXpy/awVf4qau92BVz5Ai/wt+RoOrhw6L5zXmpzz9euo4BSON2mQpU)
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  # 环境 dev:开发环境|test:测试环境|prod:生产环境
  profiles:
    active: "@profiles.active@"
  cache:
    type: ehcache
    ehcache:
      config: classpath:cache/ehcache.xml
  flyway:
    # 到新的环境中数据库中有数据，且没有flyway_schema_history表时，是否执行迁移操作,如果设置为false，在启动时会报错，并停止迁移;
    baseline-on-migrate: false
    # 是否启用flyway
    enabled: false
    #  检测迁移脚本的路径是否存在，如不存在，则抛出异常
    check-location: true
    locations: classpath:db
    clean-disabled: true
  redis:
    port: 16379
    password: ENC(o0K+mAHRQzhK+pipW5NHp+Ttt4yG3lp0FpHZkn31mCwhJApVHy1e3lxA28hZhP0Y)
    host: redis.lingxiaomz.top
  thymeleaf:
    mode: HTML5

jasypt:
  encryptor:
    password: lE1rl5K$


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true   # 开启mybatis驼峰式命名规则
    cache-enabled: true
    default-statement-timeout: 30
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: debug
jwt:
  secret: blog@Login(Auth}*^31)&lingxiao% # 登录校验的密钥
  pubKeyPath: D:\\rsakey\\rsa.pub  # 公钥地址
  priKeyPath: D:\\rsakey\\rsa.pri  # 私钥地址
  expire: 30 # 过期时间,单位分钟
  cookieName: BLOG_COOKIE # cookie的名字
  cookieMaxAge: 30 # cookie的有效时长

oss:
  accessKey: ENC(CDrAPbLn1ms26K8bV1+YftOxb4JkrtfdSfa6/Rk60D9sPM8Fz5yM0SctICOGdYwlm66En2719qfoD8/cv4xbeJJkI930D1q3533zYxNKYwI=) # 设置好账号的ACCESS_KEY和SECRET_KEY
  secretKey: ENC(xKj7NFWTv+frIYmyHb6/uK7p94g2N4FHJGcAtlW0vVRr8ueBbtcNNWSEuOXof5UPNBH7o6TJOzR7PmiesU7EdLTnA80G+XBrM6UhBZ8zYiw=)
  bucketName: function  # 要上传的空间
  prefixImg: http://img.lingxiaomz.top/
  temporaryFolder: D:\bingImage\

email:
  title: '注册博客'
  minute: 5  #邮件有效时间  单位：分钟


cors:
  allowedOrigins:
    - "http://blog.lingxiaomz.top"
    - "http://www.lingxiaomz.top"
    - "http://api.lingxiaomz.top"
    - "http://blog.test.lingxiaomz.top"
    - "https://blog.lingxiaomz.top"
    - "https://www.lingxiaomz.top"
    - "https://api.lingxiaomz.top"
  allowedMethods:
    - "OPTIONS"
    - "HEAD"
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
  ignorePaths:
    - "/css/**"
    - "/js/**"
    - "/config/**"
    - "/index.html"
    - "/img/**"
    - "/fonts/**"
    - "/favicon.ico"
    - "/verifyCode"
    - "/upload/bingImage"
    - "/upload/bingImage/random"
    - "/image/**"
    - "/user/register"
    - "/user/email/**"
    - "/swagger-ui.html"
    - "/swagger-resources/*"
    - "/webjars/*"
    - "/v2/api-docs*"
    - "/doc.html"
    - "/error/**"
    - "/front/**"
nacos:
  config:
    server-addr: 81.68.255.230:8848




