server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true   # 开启mybatis驼峰式命名规则
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: debug
  config: classpath:logback.xml
jwt:
  secret: blog@Login(Auth}*^31)&lingxiao% # 登录校验的密钥
  pubKeyPath: rsakey/rsa.pub  # 公钥地址
  priKeyPath: rsakey/rsa.pri  # 私钥地址
  expire: 30 # 过期时间,单位分钟
  cookieName: BLOG_COOKIE # cookie的名字
  cookieMaxAge: 30 # cookie的有效时长

oss:
  accessKey: V_ZleIlYzHPjekmAuRvDkkXLdV_MDkk69VZWM12f # 设置好账号的ACCESS_KEY和SECRET_KEY
  secretKey: U8SndxcceqMZGIKvhfPL3gEPkYRN_NhrP75cJlOH
  bucketName: function  # 要上传的UrlAccessDecisionManager空间
  prefixImg: http://img.lingxiaomz.top/

email:
  title: '注册博客'
  minute: 5  #邮件有效时间  单位：分钟