server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: debug
jwt:
  secret: blog@Login(Auth}*^31)&lingxiao% # 登录校验的密钥
  pubKeyPath: D:\\rsakey\\rsa.pub  # 公钥地址
  priKeyPath: D:\\rsakey\\rsa.pri  # 私钥地址
  expire: 30 # 过期时间,单位分钟
  cookieName: LEYOU_COOKIE # cookie的名字
  cookieMaxAge: 30 # cookie的有效时长