version: '3.4'   # compose文件版本格式和docker版本兼容
services:
  blog:
    build: ./
    ports:
      - "8081:8081"
    volumes:
      - "/blog/log:/log"
    depends_on:
      - redis
      - db
      - nginx-web
  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    deploy:
      restart_policy:
        delay: 10s
    command: redis-server --requirepass lingxiao
    volumes:
      - "/home/redis/data:/data"
  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  nginx-web:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "/home/nginx/www:/usr/share/nginx/html"
      - "/home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/nginx/logs:/var/log/nginx"
      - "/www/wwwroot/blog:/www/wwwroot/blog"
    network_mode: "host"