version: '3.4'   # compose文件版本格式和docker版本兼容
services:
  blog:
    build: ./
    ports:
      - "8081:8081"
    volumes:
      - "/blog/log:/log"
    depends_on:
      - redis
      - db
      - nginx_web
  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    deploy:
      restart_policy:
        delay: 10s
    command: redis-server --requirepass lingxiao
    volumes:
      - "/home/redis/data:/data"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  nginx_web:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    volumes:
      - "/home/nginx/www:/usr/share/nginx/html"
      - "/home/nginx/logs:/var/log/nginx"
      - "/www/wwwroot:/www/wwwroot"
    network_mode: host